!ABCIncludeFile(SuperClass)

  INCLUDE('CL_Property.inc'),ONCE
  INCLUDE('CL_PropertyList.inc'),ONCE

  INCLUDE('CL_Property_Bool.inc'),ONCE
  INCLUDE('CL_Property_Byte.inc'),ONCE
  INCLUDE('CL_Property_Date.inc'),ONCE
! INCLUDE('CL_Property_Duration.inc'),ONCE
  INCLUDE('CL_Property_Long.inc'),ONCE
  INCLUDE('CL_Property_Real.inc'),ONCE
  INCLUDE('CL_Property_String.inc'),ONCE
  INCLUDE('CL_Property_StringTheory.inc'),ONCE
  INCLUDE('CL_Property_Time.inc'),ONCE

